const CONCEPTS=[
 {topic:"Asymptotics & Growth",opts:["True","False"],items:[
  ["2.5ⁿ = Θ(2ⁿ)","False","2.5ⁿ/2ⁿ = 1.25ⁿ → ∞. Exponentials with different bases are never Θ-equivalent.",null,"Short test 1 · P2a",null],
  ["n² = Θ(4^(lg n))","True","4^(lg n) = 2^(2·lg n) = n². They are literally the same function.",null,"Short test 1 · P2b",null],
  ["n·2ⁿ = o(2ⁿ)","False","The ratio (n·2ⁿ)/2ⁿ = n → ∞, so it is ω(2ⁿ), the opposite of o.",null,"Short test 1 · P2c",null],
  ["n! = ω(2ⁿ)","True","n! beats every exponential: n!/2ⁿ → ∞ (Stirling).",null,"Short test 1 · P2d",null],
  ["f(n) = Ω(f(n))","True","Reflexive — take c = 1, since f(n) ≥ 1·f(n).",null,"Short test 1 · P2e",null],
  ["f(n) = ω(f(n))","False","ω is strict and would need f/f → ∞, but the ratio is always 1.",null,"Short test 1 · P2f",null],
  ["f(n) = O(g(n)) implies g(n) = O(f(n))","False","O is not symmetric: n = O(n²) but n² ≠ O(n).",null,"Short test 1 · P2g",null],
  ["f(n) = O(g(n)) and g(n) = O(h(n)) implies f(n) = O(h(n))","True","O is transitive — multiply the two constants.",null,"Short test 1 · P2h",null],
  ["f(n) = o(g(n)) if and only if g(n) = ω(f(n))","True","o and ω are duals; both say f/g → 0.",null,"Short test 1 · P2i",null],
  ["There exist f,g with f(n)=Θ(g(n)) and f(n)=o(g(n))","False","Θ forces f/g → a positive constant, o forces f/g → 0. Mutually exclusive.",null,"Bonus Test 1 · P9b",null],
  ["There exist f,g with f(n)=o(g(n)) and f(n)≠Θ(g(n))","True","o(g) always rules out Θ(g); e.g. f = n, g = n².",null,"Bonus Test 1 · P9c",null],
  ["There exist f,g with f(n)=Θ(g(n)) and f(n)≠O(g(n))","False","Θ is defined as O and Ω together, so Θ always implies O.",null,"Bonus Test 1 · P9d",null],
  ["There exist f,g with f(n)=Ω(g(n)) and f(n)≠O(g(n))","True","e.g. f = n², g = n: bounded below by g but not above.",null,"Bonus Test 1 · P9e",null],
  ["2^(2n) = O(2ⁿ)","False","2^(2n) = (2ⁿ)², so the ratio is 2ⁿ → ∞ — not a constant factor.",null,"Bonus Test 1 · P9h",null],
  ["(log n)^(log n) = Θ(n^(log log n))","True","Take logs of both: each gives log n · log log n.",null,"Bonus Test 1 · P9i",null],
  ["2^(n+1) = O(2ⁿ)","True","2^(n+1) = 2·2ⁿ — just a constant factor of 2.",null,"Bonus Test 1 · P9j",null],
  ["πⁿ = O(n!)","True","n! eventually outgrows any fixed exponential cⁿ.",null,"Bonus Test 1 · P9k",null],
  ["log n = Θ(log²n)","False","log²n / log n = log n → ∞, so log²n grows strictly faster.",null,"Bonus Test 1 · P9l",null],
  ["n^(log n) = Θ(2^(n−1))","False","Compare logs: (log n)² vs n−1. The linear term dominates.",null,"Bonus Test 1 · P9m",null],
  ["2ⁿ = Θ(3ⁿ)","False","3ⁿ/2ⁿ = 1.5ⁿ → ∞.",null,"Bonus Test 1 · P9n",null],
  ["Any recurrence relation can be solved using the Master Method.","False","It needs the form aT(n/b)+f(n) and fails in the gap cases, e.g. T(n)=2T(n/2)+n log n.",null,"Short test 1 · P8c",null],
 ]},
 {topic:"Complexity of Pseudocode",opts:["Θ(1)","Θ(log n)","Θ(n)","Θ(n log n)","Θ(n²)"],items:[
  ["EXAMPLE1(n): sum←0; for i←1 to n: for j←1 to n: sum++","Θ(n²)","Both loops run n times independently → n·n iterations.",null,"Bonus test 1 · P1a",null],
  ["EXAMPLE2(n): sum←0; for i←1 to n: for j←1 to i: sum++","Θ(n²)","The inner loop runs i times, so the total is 1+2+…+n = n(n+1)/2 = Θ(n²).",null,"Bonus test 1 · P1b",null],
  ["EXAMPLE3(n): sum←0; i←1; while i ≤ n: sum++; i←2i","Θ(log n)","i doubles every round, so it reaches n after lg n steps.",null,"Bonus test 1 · P1c",null],
  ["FUNC(i,j): if i<j { mid←⌊(i+j)/2⌋; sum++; FUNC(i,mid); FUNC(mid+1,j) }, called as FUNC(1,n)","Θ(n)","T(n) = 2T(n/2) + Θ(1) → Master case 1 gives Θ(n): the recursion tree has Θ(n) leaves and O(1) work per node.",null,"Bonus test 1 · P1d",null],
 ]},
 {topic:"Identify the Sorting Algorithm",opts:["MergeSort","HeapSort","InsertionSort","BubbleSort"],items:[
  ["[8,4,5,1,2,7,6,3] → [4,8,5,1,2,7,6,3] → [4,5,8,1,2,7,6,3] → [1,4,5,8,2,7,6,3] → [1,2,4,5,8,7,6,3]","InsertionSort","A sorted prefix grows by one element per step while the unsorted tail is untouched — the signature of InsertionSort.",null,"Bonus test 1 · P5a",null],
  ["[8,4,5,1,2,7,6,3] → [8,4,7,3,2,5,6,1] → [7,4,6,3,2,5,1,8] → [6,4,5,3,2,1,7,8] → [5,4,1,3,2,6,7,8]","HeapSort","The first step build-heaps the array; after that the largest element is parked at the end each round and the suffix grows sorted.",null,"Bonus test 1 · P5b",null],
 ]},
 {topic:"SELECT — median of medians",opts:["<",">","?"],items:[
  ["a ◦ b","?","a and b sit in different groups, and neither is connected to the other through the arrow chains — the relation is unknown.",["<",">","?"],"Bonus test 1 · P9a","fig-select"],
  ["a ◦ c","?","Both lie above their group medians but in different columns; nothing forces an order between them.",["<",">","?"],"Bonus test 1 · P9b","fig-select"],
  ["a ◦ d","<","d is in the shaded region of elements known to be greater than x, and a is known to be smaller than x, so a < d.",["<",">","?"],"Bonus test 1 · P9c","fig-select"],
  ["a ◦ x","<","a lies in a column whose median is smaller than x, on the smaller side — the arrows give x → … → a, so a < x.",["<",">","?"],"Bonus test 1 · P9d","fig-select"],
  ["b ◦ c","?","b is below its median in a left column, c is above its median in a right column — no arrow path connects them.",["<",">","?"],"Bonus test 1 · P9e","fig-select"],
  ["b ◦ d","?","Both are below their own group medians in different columns, so their order is not determined.",["<",">","?"],"Bonus test 1 · P9f","fig-select"],
  ["b ◦ x","?","b is only known to be below its own group median; that median may be on either side of x.",["<",">","?"],"Bonus test 1 · P9g","fig-select"],
  ["c ◦ d","?","c is above its median and d below its own — the two columns are unordered with respect to each other here.",["<",">","?"],"Bonus test 1 · P9h","fig-select"],
  ["c ◦ x","?","c is above the median of a column whose median is greater than x, which says nothing about c versus x itself.",["<",">","?"],"Bonus test 1 · P9i","fig-select"],
  ["d ◦ x",">","d sits inside the shaded block of elements that the median-of-medians argument guarantees to be larger than x.",["<",">","?"],"Bonus test 1 · P9j","fig-select"],
 ]},
 {topic:"Recurrences",opts:["O(n)","O(n lg n)","O(n^1.5)","O(n²)","O(n² lg n)","O(n³)"],items:[
  ["Θ bound for T(n) = 8T(n/2) + n²/2","O(n³)","log₂8 = 3 and f(n)=n² = O(n^(3−ε)) → Master case 1 → Θ(n³).",null,"Retake · P2b",null],
  ["Θ bound for T(n) = 27T(n/9) + n","O(n^1.5)","log₉27 = 1.5 and f(n)=n = O(n^(1.5−ε)) → Master case 1 → Θ(n^1.5).",null,"Retake · P2c",null],
  ["Θ bound for T(n) = 4T(n/2) + n²","O(n² lg n)","log₂4 = 2 and f(n) = n² = Θ(n²) → Master case 2 → Θ(n² lg n).",["O(lg n)","O(n)","O(n lg n)","O(n^1.5)","O(n² lg n)","O(n³)"],"Final Exam · P2b",null],
  ["Θ bound for T(n) = 8T(n/4) + n","O(n^1.5)","log₄8 = 1.5 and f(n) = n = O(n^(1.5−ε)) → Master case 1 → Θ(n^1.5).",["O(lg n)","O(n)","O(n lg n)","O(n^1.5)","O(n² lg n)","O(n³)"],"Final Exam · P2c",null],
 ]},
 {topic:"Sorting",opts:["True","False"],items:[
  ["The runtime of InsertionSort is O(n log n).","False","Worst case is Θ(n²) — reverse-sorted input shifts j−1 elements on step j.",null,"Bonus Test 1 · P9f",null],
  ["Formulating InsertionSort as a recursive procedure improves its runtime.","False","Same comparisons and shifts; recursion only changes the control flow.",null,"Bonus Test 1 · P9g",null],
  ["The runtime of MERGE is O(n).","True","One pass over both halves, one comparison per output element.",null,"Bonus Test 1 · P9q",null],
  ["The runtime of MaxHeapify is Θ(n log n).","False","It sifts down a single root-to-leaf path: Θ(log n). Build-Heap is the O(n) one.",null,"Bonus Test 1 · P9r",null],
  ["Stable (or easily made stable): InsertionSort","True","It shifts only strictly-greater elements, so equal keys keep their order.",null,"Bonus Test 1 · P9o",null],
  ["Stable (or easily made stable): MergeSort","True","Ties are broken in favour of the left run during MERGE.",null,"Bonus Test 1 · P9o",null],
  ["Stable (or easily made stable): HeapSort","False","Sift-down swaps far-apart elements, destroying the order of equal keys.",null,"Bonus Test 1 · P9o",null],
  ["In-place (or easily made in-place): InsertionSort","True","Sorts within the array using O(1) extra space.",null,"Bonus Test 1 · P9p",null],
  ["In-place (or easily made in-place): MergeSort","False","MERGE needs an O(n) auxiliary buffer.",null,"Bonus Test 1 · P9p",null],
  ["In-place (or easily made in-place): HeapSort","True","The heap lives in the array itself; it only swaps.",null,"Bonus Test 1 · P9p",null],
  ["In QuickSort, always using the last element of the sub-array as pivot gives worst-case recursion depth Θ(log n).","False","On already-sorted input the split is 0 / n−1, so the depth is Θ(n).",null,"Bonus Test 2 · P8c",null],
  ["BucketSort runs in expected linear time if the input has uniform distribution.","True","Uniform keys give ~1 element per bucket, so per-bucket sorting is O(1) expected.",null,"Bonus Test 2 · P8d",null],
  ["BucketSort can sort an arbitrary collection of numbers in O(n) time.","False","Without uniformity every key can land in one bucket → Θ(n²).",null,"Retake · P10d",null],
  ["Any comparison-based sorting algorithm requires Ω(n lg n) time for input size n.","True","A decision tree with n! leaves has height ≥ lg(n!) = Ω(n lg n).",null,"Short test 1 · P8f",null],
  ["Counting sort is stable.","True","Scanning the input right-to-left while decrementing counts preserves order.",null,"Bonus Test 2 · P8j",null],
  ["Sorting an array of n integers in the range [0, n²−1] runs in Ω(n lg n) time.","False","Radix sort in base n does it in O(n); the bound only binds comparison sorts.",null,"Bonus Test 2 · P8l",null],
  ["The minimum, maximum, and median elements can be found in Θ(n) time.","True","Min/max by a scan; median by SELECT (median-of-medians) in linear time.",null,"Bonus Test 2 · P8e",null],
  ["2(n−1) is the lower bound for the comparisons needed to find both the min and max of n distinct integers.","False","Pairing elements first needs only ⌈3n/2⌉−2, which is fewer.",null,"Bonus Test 2 · P8k",null],
 ]},
 {topic:"Heaps",opts:["True","False"],items:[
  ["There exists a heap T storing seven distinct elements whose rLR traversal yields them in sorted order.","True","rLR visits right subtree, then left, then root — a suitable max-heap makes that increasing.",null,"Bonus Test 1 · P9a",null],
  ["The sequence [23,17,14,6,13,10,1,5,7,12] is a max-heap.","False","A[4]=6 has child A[9]=7, so a parent is smaller than its child.",null,"Short test 1 · P8i",null],
  ["A min-heap can be represented by an array.","True","It is a complete tree, so children of i sit at 2i and 2i+1.",null,"Retake · P10l",null],
  ["An array sorted in decreasing order is a min-heap.","False","Decreasing order is a max-heap; a min-heap needs parent ≤ children.",null,"Final Exam · P13l",null],
 ]},
 {topic:"Heap sizes",items:[
  ["What is the height h of a heap of size n?","⌊log n⌋","Halving the index from n up to the root takes ⌊lg n⌋ steps.",["2ⁿ","n","⌊n/2⌋","⌊log n⌋"],"Short test 1 · P7a",null],
  ["What is the largest size n for a heap with height h?","2^(h+1) − 1","Every level 0..h is completely filled.",["2ʰ","2^(h+1) − 1","2h − 1","⌊log h⌋ + 1"],"Short test 1 · P7b",null],
  ["What is the smallest size n for a heap with height h?","2ʰ","Levels 0..h−1 full (2ʰ−1 nodes) plus a single node on level h.",["2ʰ","h","h²","2^(h+1) − 1"],"Short test 1 · P7c",null],
 ]},
 {topic:"Trees",opts:["True","False"],items:[
  ["A full binary tree is complete.","False","Full only means every node has 0 or 2 children — the leaves may sit at different depths.",null,"Bonus Test 2 · P8a",null],
  ["A complete binary tree is full.","True","With every level filled, every internal node has exactly two children.",null,"Bonus Test 2 · P8b",null],
  ["Given the sequence (v₁,…,vₙ) of a binary tree traversal by LrR, one can reconstruct the exact structure of the tree.","False","Inorder alone is ambiguous — many shapes give the same sequence. You need a second traversal.",null,"Retake · P10g",null],
 ]},
 {topic:"Tree Traversals",opts:["Preorder","Postorder","Inorder","None of the above"],items:[
  ["{C, B, D, A, F, E, H, G, I}","Inorder","Whole left subtree, then the root A, then the right subtree.",null,"Bonus Test 2 · P9a",null],
  ["{H, D, B, E, F, I, C, G, A}","None of the above","It matches no pre-, post- or in-order walk of this tree.",null,"Bonus Test 2 · P9b",null],
  ["{A, B, C, D, E, F, G, H, I}","Preorder","Root A first, then the left subtree, then the right.",null,"Bonus Test 2 · P9c",null],
  ["{A, B, E, C, D, F, G, H, I}","None of the above","Starts like preorder but the sibling order is wrong.",null,"Bonus Test 2 · P9d",null],
  ["{C, D, B, F, H, I, G, E, A}","Postorder","Both subtrees are emitted before the root A, which comes last.",null,"Bonus Test 2 · P9e",null],
 ]},
 {topic:"Data Structure Operations",opts:["O(1)","O(log n)","O(n)","O(n log n)"],items:[
  ["PUSH in a stack","O(1)","Write at the top pointer.",null,"Retake · P1a",null],
  ["ENQUEUE in a queue","O(1)","Append at the tail pointer.",null,"Retake · P1b",null],
  ["APPEND in an unsorted array","O(1)","Write at the end — memory is assumed sufficient.",null,"Retake · P1c",null],
  ["INSERT in a priority queue","O(log n)","Place at the end, then sift up one heap path.",null,"Retake · P1d",null],
  ["FIND_MIN in a stack","O(n)","A stack keeps no order information, so every element must be scanned.",null,"Retake · P1e",null],
  ["FIND_MIN in a queue","O(n)","A queue keeps no order information, so every element must be scanned.",null,"Retake · P1f",null],
  ["INSERT at an arbitrary position in an unsorted array","O(n)","All following elements have to be shifted right.",null,"Retake · P1g",null],
  ["FIND_MIN in a priority queue","O(1)","The minimum is simply the root of the min-heap.",null,"Retake · P1h",null],
  ["POP in a stack","O(1)","Remove at the top pointer.",null,"Retake · P1i",null],
  ["DEQUEUE in a queue","O(1)","Remove at the head pointer.",null,"Retake · P1j",null],
  ["SEARCH in a sorted array","O(log n)","Binary search halves the range each step.",null,"Retake · P1k",null],
  ["SEARCH in a priority queue","O(n)","Heap order says nothing about siblings, so an arbitrary key needs a full scan.",null,"Retake · P1l",null],
  ["INSERT in a linked list (at the head)","O(1)","Re-point the head; no traversal is needed.",null,"Final Exam · P1a",null],
  ["INSERT in a hash table","O(1)","Hash the key and prepend it to that bucket's list.",null,"Final Exam · P1b",null],
  ["INSERT in a binary search tree","O(n)","Worst case the BST is a path, so the insertion walks all n nodes.",null,"Final Exam · P1c",null],
  ["INSERT in a heap","O(log n)","Append at the end, then sift up one root-to-leaf path.",null,"Final Exam · P1d",null],
  ["FIND_MIN in a linked list","O(n)","Unordered — every node has to be inspected.",null,"Final Exam · P1e",null],
  ["FIND_MIN in a hash table","O(n)","Hashing destroys order, so all n keys must be scanned.",null,"Final Exam · P1f",null],
  ["FIND_MIN in a binary search tree","O(n)","Walk left until you cannot — that is the height, which is Θ(n) for a degenerate tree.",null,"Final Exam · P1g",null],
  ["FIND_MIN in a heap","O(1)","In a min-heap the minimum is the root.",null,"Final Exam · P1h",null],
  ["DELETE in a linked list","O(n)","Finding the node with the given key is a linear scan.",null,"Final Exam · P1i",null],
  ["DELETE in a hash table","O(n)","Worst case every key collides into one bucket, so the bucket scan is linear.",null,"Final Exam · P1j",null],
  ["DELETE in a binary search tree","O(n)","The search for the node costs the height, which is Θ(n) in the worst case.",null,"Final Exam · P1k",null],
  ["DELETE in a heap","O(log n)","Swap with the last element, shorten the array, then sift down one path.",null,"Final Exam · P1l",null],
 ]},
 {topic:"Linked Lists",opts:["True","False"],items:[
  ["ListSearch in a linked list runs in O(1) time.","False","There is no random access — you walk the list, O(n).",null,"Bonus Test 2 · P8f",null],
  ["ListPrepend in a linked list runs in O(1) time.","True","Splice the new node in at the head pointer.",null,"Bonus Test 2 · P8g",null],
  ["ListDelete in a singly linked list runs in O(1) time.","False","You need the predecessor to relink, and finding it costs O(n).",null,"Bonus Test 2 · P8h",null],
  ["ListDelete in a doubly linked list runs in O(1) time.","True","The prev pointer lets you relink both neighbours directly.",null,"Bonus Test 2 · P8i",null],
 ]},
 {topic:"Red-Black Trees & BST",opts:["True","False"],items:[
  ["Any BST storing n numbers can be transformed into any other BST with these n numbers using rotations.","True","Rotations can lift any key to the root, then recurse on the subtrees; O(n) rotations suffice.",null,"Bonus Test 3 · P8d",null],
  ["It is possible that a leaf in a red-black tree is twice as deep as another leaf in the same tree.","True","Longest path (alternating red/black) is at most twice the shortest (all black) — 2× is attainable.",null,"Short test 3 · P8c",null],
  ["It is possible that a leaf in a red-black tree is three times as deep as another leaf in the same tree.","False","The same 2× bound forbids any ratio beyond two.",null,"Bonus Test 3 · P9a",null],
  ["Given a red-black tree with black-height k, the largest possible number of internal nodes is 2^(2k)−1.","True","Maximum height is 2k, so at most a full tree of that height.",null,"Bonus Test 3 · P9b",null],
  ["Given a red-black tree with black-height k, the smallest possible number of internal nodes is 2k.","False","The minimum is 2ᵏ−1, given by the all-black tree of height k.",null,"Bonus Test 3 · P9c",null],
  ["Given a red-black tree with black-height k≥2, the maximum ratio between two subtrees is Θ(2ᵏ).","True","One side can be all-black of height k while the other reaches height 2k using red nodes.",null,"Bonus Test 3 · P9d",null],
  ["A red-black tree with more than 1 element built with RB-Insert contains at least one red node.","True","New nodes are inserted red, and with n>1 they cannot all be recoloured away.",null,"Bonus Test 3 · P9e",null],
  ["The height of a node is the number of edges in a longest path to a leaf.","True","That is the standard definition of node height.",null,"Bonus Test 3 · P9f",null],
  ["The black-height of a node x counts the black nodes including the sentinel nil[T] and x on a path from x to a leaf.","False","Black-height excludes x itself — it counts black nodes below x down to and including nil.",null,"Bonus Test 3 · P9g",null],
  ["A red-black tree with n internal nodes has height ≤ 2·lg(n+1).","True","Black-height is ≥ h/2 and a tree of black-height b has ≥ 2^b − 1 internal nodes.",null,"Bonus Test 3 · P9h",null],
  ["Some leaves of a red-black tree can be red.","False","All leaves are the nil sentinel, which is black by definition.",null,"Bonus Test 3 · P9i",null],
  ["To save space, a single sentinel nil[T] can be used for all leaves.","True","The standard CLRS optimisation — one shared black sentinel node.",null,"Bonus Test 3 · P9j",null],
  ["The root's parent is nil[T].","True","The same sentinel also serves as the parent of the root.",null,"Bonus Test 3 · P9k",null],
  ["Deleting a black node requires no fix-up.","False","Removing a black node breaks the black-height invariant, so RB-Delete-Fixup must run.",null,"Bonus Test 3 · P9l",null],
 ]},
 {topic:"BST Rotations",opts:["O(1)","O(lg n)","O(n)","O(n lg n)","O(n²)"],items:[
  ["Maximum number of rotations needed to transform any BST on n vertices into any other BST?","O(n)","Rotate the first tree into a right spine (O(n)), then rotate down into the target (O(n)).",null,"Retake · P13b",null],
 ]},
 {topic:"Hashing",items:[
  ["Uniform hash into 1..n — likelihood a new element x is assigned a particular index i?","1 / n","Uniform means each of the n slots is equally likely.",["1 / n","n","1 / i","1 / C(n,2)"],"Bonus Test 2 · P8m",null],
  ["How many elements must be added to the hash table to ensure a collision?","n + 1","Pigeonhole principle: n slots but n+1 items.",["n","n + 1","2n","2n + 1"],"Bonus Test 2 · P8n",null],
  ["With k unique elements already present and no collisions, likelihood the next insert causes a collision?","k / n","Exactly k of the n slots are occupied.",["1 / n","n / k","C(k,2)","k / n"],"Bonus Test 2 · P8o",null],
 ]},
 {topic:"Dynamic Programming",opts:["True","False"],items:[
  ["The matrix-chain multiplication problem exhibits overlapping sub-problems.","True","The same subchain Aᵢ..Aⱼ is re-solved under many different split points.",null,"Bonus Test 3 · P8e",null],
  ["The longest common subsequence problem exhibits the greedy-choice property.","False","A locally longest match can block a better global alignment, so LCS needs DP.",null,"Bonus Test 4 · P8j",null],
  ["The longest path problem exhibits the optimal substructure property.","False","Subpaths of a longest path need not be longest, because vertices may not repeat.",null,"Short test 3 · P8h",null],
  ["Every optimization problem can be solved optimally with dynamic programming.","False","DP needs optimal substructure and overlapping subproblems; many problems have neither.",null,"Short test 3 · P8j",null],
  ["Matrix-Chain-Multiplication: any parenthesization of n elements has exactly n−1 pairs of parentheses.","True","Induction: multiplying n matrices takes n−1 multiplications and each contributes one pair. (n=3: ((A₁A₂)A₃) has 2.)",null,"Bonus Test 3 · P5b",null],
  ["Matrix-Chain-Multiplication: any parenthesization of n elements has exactly n pairs of parentheses.","False","It is n−1, not n — multiplying n matrices takes n−1 multiplications and each contributes one pair of parentheses.",null,"Final Exam · P13h",null],
 ]},
 {topic:"DP Properties",items:[
  ["Problems solvable by dynamic programming exhibit which two properties?","Overlapping sub-problems + Optimal substructure","Overlap is what makes memoisation pay off; optimal substructure is what makes the recurrence valid.",["Overlapping sub-problems + Optimal substructure","Greedy-choice property + Optimal substructure","Overlapping sub-problems + Independence of sub-problems","Optimal substructure + Monotone substructure"],"Bonus Test 3 · P8a",null],
  ["The rod-cutting problem has which of the following properties?","Overlapping sub-problems","The same remaining length is re-solved after many different first cuts.",["Greedy-choice property","Overlapping sub-problems","Monotone substructure"],"Bonus Test 3 · P8b",null],
  ["The matrix-chain multiplication problem has which of the following properties?","Optimal substructure","An optimal parenthesization contains optimal parenthesizations of both of its subchains.",["Optimal substructure","Monotone substructure","Independence of sub-problems"],"Bonus Test 3 · P8c",null],
 ]},
 {topic:"Greedy, MST & Huffman",opts:["True","False"],items:[
  ["The binary tree corresponding to an optimal prefix code is full.","True","A node with a single child could be replaced by that child, shortening every code below it.",null,"Bonus Test 4 · P8a",null],
  ["Every graph has a unique MST.","False","Equal edge weights allow several distinct minimum spanning trees.",null,"Bonus Test 4 · P8b",null],
  ["Prim's algorithm is an instance of GenericMST.","True","It repeatedly adds a safe edge crossing the cut (tree, rest).",null,"Bonus Test 4 · P8c",null],
  ["Kruskal's algorithm is an instance of GenericMST.","True","It repeatedly adds the lightest safe edge joining two components.",null,"Bonus Test 4 · P8d",null],
  ["The greedy algorithm for computing change with coins (25,10,5,1) is optimal.","True","The US system is canonical, so greedy provably matches the optimum.",null,"Bonus Test 4 · P8e",null],
  ["The greedy algorithm for computing change with coins (30,24,12,6) is optimal.","False","For 48 greedy gives 30+12+6 = 3 coins, but 24+24 = 2 coins is better.",null,"Bonus Test 4 · P8f",null],
  ["The greedy algorithm for computing change with coins (27,9,3,1) is optimal.","True","Each coin is a multiple of the next (powers of 3), which makes greedy optimal.",null,"Bonus Test 4 · P8g",null],
  ["Huffman's algorithm creates an optimal prefix code.","True","Exchange argument: merging the two least frequent symbols is always a safe choice.",null,"Bonus Test 4 · P8h",null],
  ["The Shannon-Fano algorithm creates an optimal prefix code.","False","Top-down splitting can be suboptimal; only Huffman's bottom-up merge guarantees optimality.",null,"Bonus Test 4 · P8i",null],
  ["If all edges in a graph have unique weights, then there is a unique MST.","True","The cut and cycle properties then force a single choice at every step.",null,"Retake · P10j",null],
  ["If all edges in a graph have unique weights, then there is a unique NST (next-to-best spanning tree).","False","Distinct edge weights do not stop two different swaps from tying for second best.",null,"Final Exam · P13k",null],
  ["Given G=(V,E), any tree T=(V,E*) with E*⊆E is a minimum spanning tree of G.","False","It is a spanning tree, but nothing forces its total weight to be minimum.",null,"Retake · P10c",null],
  ["If an edge is the unique lightest edge crossing some cut of a connected undirected graph, it belongs to every MST.","True","Cut property — swapping it into any tree without it strictly reduces the weight.",null,"Short test 5 · P9c",null],
  ["The lower bound for computing the Convex Hull of n points is Ω(n lg n).","True","Sorting reduces to convex hull, so the sorting bound carries over.",null,"Short test 3 · P8e",null],
 ]},
 {topic:"Disjoint Sets",opts:["True","False"],items:[
  ["MakeSet(x) runs in O(1) time.","True","It just creates a one-element list with x as its own representative.",null,"Bonus Test 4 · P8k",null],
  ["Union(x,y) runs in O(1) time.","False","Appending one list to the other must update the representative pointer of every element moved.",null,"Bonus Test 4 · P8l",null],
  ["FindSet(x) runs in O(1) time.","True","Each element stores a direct pointer to its set representative.",null,"Bonus Test 4 · P8m",null],
  ["A sequence of m MakeSet/Union/FindSet operations, n of which are MakeSet, takes O(m + n lg n) time.","True","With weighted union each element's representative is updated at most lg n times.",null,"Bonus Test 4 · P8n",null],
 ]},
 {topic:"Algorithmic Paradigms",opts:["Divide-and-Conquer","Incremental","Other"],items:[
  ["SelectionSort","Incremental","It grows a sorted prefix one element at a time.",null,"Bonus Test 1 · P5a",null],
  ["QuickSort","Divide-and-Conquer","Partition splits the array, then it recurses on both sides.",null,"Bonus Test 1 · P5b",null],
  ["InsertionSort","Incremental","Each new element is inserted into the already-sorted prefix.",null,"Bonus Test 1 · P5c",null],
  ["MergeSort","Divide-and-Conquer","Split in half, sort each half, then merge.",null,"Bonus Test 1 · P5d",null],
  ["Partition","Other","A single linear rearrangement pass — neither recursive nor prefix-growing.",null,"Bonus Test 1 · P5e",null],
  ["Binary Search","Divide-and-Conquer","It discards half of the search range at every step.",null,"Bonus Test 1 · P5f",null],
  ["HeapSort","Other","It neither splits the problem in half nor grows a sorted prefix — it repeatedly extracts the max from a heap.",null,"Bonus test 1 · P6c",null],
 ]},
 {topic:"Algorithm Types",opts:["Divide & Conquer","Dynamic Programming","Greedy"],items:[
  ["Tarjan's Select","Divide & Conquer","Median-of-medians splits into groups of 5 and recurses on one side.",null,"Retake · P4d",null],
  ["QuickSort","Divide & Conquer","Partition splits the array around a pivot, then it recurses on both sides.",null,"Bonus Test 4 · P9a",null],
  ["Fractional Knapsack (thief with fractions of items)","Greedy","Taking the best value/weight ratio first is provably safe.",null,"Bonus Test 4 · P9b",null],
  ["0-1 Knapsack (thief with whole items)","Dynamic Programming","Indivisible items break the greedy choice, so you need a table over capacity.",null,"Bonus Test 4 · P9c",null],
  ["Optimal Activity Scheduling","Greedy","Always picking the earliest finishing time is a safe choice.",null,"Bonus Test 4 · P9d",null],
  ["Shannon-Fano Encoding","Divide & Conquer","It recursively splits the symbol set into halves of near-equal probability.",null,"Bonus Test 4 · P9e",null],
  ["Huffman Encoding","Greedy","It repeatedly merges the two least frequent nodes.",null,"Bonus Test 4 · P9f",null],
  ["Optimal Rod Cutting","Dynamic Programming","Overlapping subproblems on the remaining rod length.",null,"Bonus Test 4 · P9g",null],
  ["Prim's Algorithm","Greedy","It always adds the lightest edge leaving the current tree.",null,"Bonus Test 4 · P9h",null],
  ["Kruskal's Algorithm","Greedy","It always adds the lightest edge that joins two components.",null,"Bonus Test 4 · P9i",null],
  ["Optimal Matrix Chain Order","Dynamic Programming","A table m[i,j] over all subchains, reusing shared subproblems.",null,"Final Exam · P7h",null],
  ["Dijkstra's Algorithm","Greedy","It always finalises the closest unvisited vertex.",null,"Final Exam · P7i",null],
  ["Longest Common Subsequence","Dynamic Programming","A table c[i,j] over all prefix pairs.",null,"Retake · P4g",null],
  ["Optimal Polygon Triangulation","Dynamic Programming","Same recurrence shape as matrix-chain multiplication.",null,"Retake · P4h",null],
 ]},
 {topic:"Complexity Bounds",opts:["O(lg n)","O(n)","O(n lg n)","O(n²)","O(n³)","O(2ⁿ)"],items:[
  ["Optimal Rod Cutting","O(n²)","n subproblems, each trying up to n first cuts.",null,"Bonus Test 3 · P6d",null],
  ["Longest Common Subsequence","O(n²)","Fill an n×m table with O(1) work per cell.",null,"Bonus Test 3 · P6e",null],
  ["Multiplying two n×n matrices","O(n³)","The classical triple loop (ignoring Strassen).",null,"Bonus Test 3 · P6f",null],
  ["Optimal Matrix Chain Multiplication","O(n³)","O(n²) table entries, each scanning O(n) split points.",null,"Bonus Test 3 · P6g",null],
  ["Enumerating all Rod Cutting solutions","O(2ⁿ)","Each of the n−1 cut positions is independently in or out.",null,"Bonus Test 3 · P6h",null],
  ["Huffman's Algorithm","O(n lg n)","n−1 merges, each doing two extract-mins on a heap.",null,"Bonus Test 4 · P6a",null],
  ["Optimal Activity Selection (input already sorted by finish time)","O(n)","A single greedy scan once the sorting is given.",null,"Bonus Test 4 · P6b",null],
  ["Optimal Polygon Triangulation","O(n³)","Same DP shape as matrix-chain: O(n²) entries × O(n) splits.",null,"Bonus Test 4 · P6c",null],
  ["Longest Palindromic Subsequence","O(n²)","It is the LCS of the string with its own reverse.",null,"Bonus Test 4 · P6d",null],
  ["Minimum number of points so every interval contains at least one point","O(n lg n)","Sort by right endpoint, then one greedy scan.",null,"Bonus Test 4 · P6e",null],
  ["Minimum Water Stops","O(n)","One greedy pass over the stops, taking the farthest reachable each time.",null,"Bonus Test 4 · P6f",null],
  ["Convex Hull","O(n lg n)","Graham scan: sort the points, then one linear stack pass — and Ω(n lg n) is also the lower bound.",null,"Bonus test 2 · P7e",null],
  ["Optimal Parenthesization","O(n³)","Same DP as matrix-chain order: O(n²) subchains, each scanning O(n) split points.",null,"Bonus test 2 · P7i",null],
 ]},
 {topic:"Complexity — Search",opts:["O(1)","O(lg n)","O(√n)","O(n)","O(n lg n)","O(n²)"],items:[
  ["FIND in a BST","O(n)","An unbalanced BST can degenerate into a path.",null,"Bonus Test 3 · P6a",null],
  ["FIND in a Red-Black tree","O(lg n)","The height is bounded by 2·lg(n+1).",null,"Bonus Test 3 · P6b",null],
  ["DELETE in a Red-Black tree, given a pointer to the node","O(lg n)","Splice the node out, then O(log n) fix-up rotations and recolourings.",null,"Bonus Test 3 · P6c",null],
  ["Worst-case runtime of BST-SUCCESSOR (return the leftmost node of the right subtree, otherwise walk up until x is a left child)","O(n)","Both branches follow one root-to-leaf path, and an unbalanced BST has height Θ(n).",["O(lg n)","O(n)","O(n lg n)","O(n²)"],"Bonus test 2 · P5b",null],
 ]},
 {topic:"Complexity — Graphs",opts:["O(n)","O(n lg n)","O(n²)","O(n² lg n)","O(n³)","O(n!)"],items:[
  ["Tarjan's Select","O(n)","Median-of-medians selection runs in worst-case linear time.",null,"Retake · P9a",null],
  ["Topological Sort","O(n²)","Θ(V+E), and expressed in n alone E = O(n²).",null,"Retake · P9b",null],
  ["Depth-first Search","O(n²)","Θ(V+E), and expressed in n alone E = O(n²).",null,"Retake · P9c",null],
  ["Find Longest Path","O(n!)","NP-hard — brute force enumerates vertex orderings.",null,"Retake · P9d",null],
  ["Multiply an n×n matrix by an n×n matrix","O(n³)","The classical triple loop.",null,"Retake · P9e",null],
  ["Mergesort","O(n lg n)","T(n) = 2T(n/2) + n.",null,"Retake · P9f",null],
  ["Quicksort","O(n²)","Worst case when the pivot always splits 0 / n−1.",null,"Retake · P9g",null],
  ["Single-source Shortest Path in an unweighted graph","O(n²)","BFS is Θ(V+E), and E = O(n²) in terms of n.",null,"Retake · P9h",null],
  ["Single-source Shortest Path in a weighted graph","O(n² lg n)","Dijkstra with a binary heap is O((V+E)·lg V).",null,"Retake · P9i",null],
  ["Floyd-Warshall Algorithm","O(n³)","A triple loop over all intermediate vertices.",null,"Retake · P9j",null],
  ["Computing Perfect Authority with an adjacency matrix","O(n)","A perfect authority (universal sink) has in-degree n−1 and out-degree 0. Walk the matrix: each of the n−1 probes eliminates one candidate, then verify the survivor in O(n).",null,"Final Exam · P12a",null],
  ["Computing Perfect Authority with an adjacency list","O(n²)","Without O(1) edge lookups you must read the whole adjacency structure, i.e. Θ(V+E) = O(n²).",null,"Final Exam · P12b",null],
  ["Computing the diameter of a tree","O(n)","Two BFS runs: from any vertex find the farthest u, then from u find the farthest v. A tree has E = n−1, so each BFS is Θ(n).",null,"Final Exam · P12c",null],
  ["Multiply an n×n matrix by a vector","O(n²)","One dot product of length n per output entry — n² multiply-adds in total.",null,"Final Exam · P12e",null],
  ["HeapSort","O(n lg n)","Build-Heap is O(n), then n extract-max operations each costing O(lg n).",null,"Final Exam · P12f",null],
  ["Dijkstra's Algorithm","O(n² lg n)","O((V+E)·lg V) with a binary heap, and E = O(n²) when expressed in n alone.",null,"Final Exam · P12h",null],
  ["Bellman-Ford Algorithm","O(n³)","V−1 relaxation passes over all E edges: O(V·E) = n·n² = O(n³).",null,"Final Exam · P12i",null],
 ]},
 {topic:"Graphs",opts:["True","False"],items:[
  ["A DAG has no cycles.","True","Directed Acyclic Graph — acyclic is part of the definition.",null,"Retake · P10a",null],
  ["The union of all unique shortest paths from a single source in a positively weighted, connected, undirected graph is a tree.","True","Unique shortest paths give every vertex exactly one parent — a shortest-path tree.",null,"Retake · P10b",null],
  ["The union of all shortest paths (source fixed) in an undirected graph is an MST.","False","A shortest-path tree minimises distance from s, not the total edge weight.",null,"Short test 5 · P9h",null],
  ["An Eulerian cycle of a connected graph can be found in polynomial time.","True","It exists iff every degree is even, and Hierholzer's algorithm builds one in O(E).",null,"Retake · P10e",null],
  ["A Hamiltonian cycle of a connected graph can be found in polynomial time.","False","Hamiltonian cycle is NP-complete — no polynomial algorithm is known.",null,"Final Exam · P13e",null],
  ["If all edges in a graph have the same weight, then BFS computes the single-source shortest path.","True","With equal weights, fewest edges is the same as shortest distance.",null,"Retake · P10i",null],
  ["If all edges have the same weight in a connected undirected graph, BFS produces an MST.","True","When all weights are equal every spanning tree has the same total weight, so any is minimum.",null,"Short test 5 · P9a",null],
  ["The PageRank of an n-vertex graph is an n×n matrix.","False","PageRank is a vector of n probabilities; it is the transition matrix that is n×n.",null,"Retake · P10k",null],
  ["When adding an edge to a directed graph, the number of SCCs can decrease.","True","A new edge can close a cycle and merge several components into one.",null,"Retake · P10m",null],
  ["When adding an edge to a directed graph, the number of SCCs can increase.","False","Adding edges never splits an existing strongly connected component.",null,"Final Exam · P13m",null],
  ["When adding an edge to a directed graph, the number of SCCs can stay the same.","True","An edge inside an existing SCC, or one that closes no new cycle, changes nothing.",null,"Short test 5 · P9f",null],
  ["When adding an edge to a directed graph, the number of SCCs decreases by at most 1.","False","One edge closing a long chain of SCCs into a cycle can merge many at once.",null,"Short test 5 · P9g",null],
  ["The Vertex Cover algorithm that computes a matching is a 2-approximation.","True","Taking both endpoints of each matching edge is ≤ 2×, since OPT needs ≥1 endpoint per edge.",null,"Final Exam · P13a",null],
  ["Every computational problem can be solved in a finite amount of time.","False","The halting problem is undecidable.",null,"Final Exam · P13c",null],
  ["Every problem can be solved in polynomial time (in the size of the input).","False","NP-hard problems have no known polynomial algorithm, and undecidable problems have none at all.",null,"Bonus test 1 · P8j",null],
  ["Every problem in the class NP can be verified in polynomial time.","True","That is precisely the definition of NP.",null,"Final Exam · P13d",null],
 ]},
 {topic:"Shortest Paths",opts:["True","False"],items:[
  ["Dijkstra solves the SSSP problem on weighted graphs, even with some negative edge weights.","False","A vertex finalised early can still be improved later by a negative edge.",null,"Retake · P10n",null],
  ["Dijkstra can solve SSSP with negative weights if k+1 is added to every edge (−k = most negative weight).","False","Adding a constant per edge penalises paths with more edges, changing which path is shortest.",null,"Short test 5 · P9j",null],
  ["Given a weighted DAG, running BFS and relaxing all outgoing edges of v when v is dequeued correctly computes SSSP.","False","BFS dequeues in hop-count order, which is not a topological order.",null,"Short test 5 · P9d",null],
  ["For all (u,v)∈E: δ(s,v) < δ(s,u) + w(u,v).","False","The triangle inequality is stated with ≤; equality holds along a shortest path.",null,"Final Exam · P10a",null],
  ["If δ(s,v) = ∞, then d[v] = ∞ always.","True","No-path property — relaxation can never produce a finite estimate for an unreachable vertex.",null,"Final Exam · P10b",null],
  ["d[v] ≤ δ(s,v) for all v, and once d[v] = δ(s,v) it never changes.","False","The upper-bound property runs the other way: d[v] ≥ δ(s,v) at all times.",null,"Final Exam · P10c",null],
  ["If s⇝u followed by edge (u,v) is a shortest path and d[u]=δ(s,u), then after Relax(u,v,w) we have d[v]=δ(s,v).","True","The convergence property — relaxing the final edge with a correct d[u] settles v.",null,"Final Exam · P10d",null],
  ["If p=⟨v₀,…,vₖ⟩ is a shortest path and we relax (v₀,v₁),…,(vₖ₋₁,vₖ) in order, even intermixed with other relaxations, then d[vₖ]=δ(s,vₖ).","True","The path-relaxation property — order along the path is all that matters.",null,"Final Exam · P10e",null],
 ]},
 {topic:"DFS Edge Types",opts:["Case 1","Case 2","Case 3"],items:[
  ["Tree edge u→v satisfies which case of the DFS theorem?","Case 2","v is first discovered from u, so v's interval nests inside u's.",null,"Retake · P7a",null],
  ["Back edge u→v satisfies which case of the DFS theorem?","Case 3","v is an ancestor of u, so u's interval nests inside v's.",null,"Retake · P7b",null],
  ["Forward edge u→v satisfies which case of the DFS theorem?","Case 2","v is a descendant of u already finished — still nested inside u's interval.",null,"Retake · P7c",null],
  ["Cross edge u→v satisfies which case of the DFS theorem?","Case 1","The two intervals are disjoint and neither vertex is an ancestor of the other.",null,"Retake · P7d",null],
 ]},
 {topic:"Graph Figures",items:[
  ["For exactly what values of y is there a YES answer to “Does G have a Vertex Cover of size y?”","≥ 5","A minimum vertex cover of this graph has size 5, and any superset of a cover is still a cover — so YES exactly for y ≥ 5.",["≥ 3","≥ 4","≥ 5","≥ 6"],"Retake · P5b","fig-retake-p5"],
  ["How many strongly connected components are there in G?","5","The SCCs are {r}, {u}, {q,t,y}, {x,z} and {s,v,w} — five in total.",["1","2","3","4","5","6","7","8"],"Retake · P11b","fig-retake-p11"],
 ]},
];